/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : pil.g
 *     -                            On : 2012-10-05 23:50:02
 *     -                 for the lexer : pilLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
pilLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef ppilLexer, which is returned from a call to pilLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in ppilLexer are  as follows:
 *
 *  - 
 void
      ppilLexer->T__19(ppilLexer)
 *  - 
 void
      ppilLexer->T__20(ppilLexer)
 *  - 
 void
      ppilLexer->T__21(ppilLexer)
 *  - 
 void
      ppilLexer->T__22(ppilLexer)
 *  - 
 void
      ppilLexer->T__23(ppilLexer)
 *  - 
 void
      ppilLexer->T__24(ppilLexer)
 *  - 
 void
      ppilLexer->T__25(ppilLexer)
 *  - 
 void
      ppilLexer->T__26(ppilLexer)
 *  - 
 void
      ppilLexer->T__27(ppilLexer)
 *  - 
 void
      ppilLexer->T__28(ppilLexer)
 *  - 
 void
      ppilLexer->T__29(ppilLexer)
 *  - 
 void
      ppilLexer->T__30(ppilLexer)
 *  - 
 void
      ppilLexer->T__31(ppilLexer)
 *  - 
 void
      ppilLexer->T__32(ppilLexer)
 *  - 
 void
      ppilLexer->T__33(ppilLexer)
 *  - 
 void
      ppilLexer->T__34(ppilLexer)
 *  - 
 void
      ppilLexer->T__35(ppilLexer)
 *  - 
 void
      ppilLexer->T__36(ppilLexer)
 *  - 
 void
      ppilLexer->T__37(ppilLexer)
 *  - 
 void
      ppilLexer->T__38(ppilLexer)
 *  - 
 void
      ppilLexer->T__39(ppilLexer)
 *  - 
 void
      ppilLexer->T__40(ppilLexer)
 *  - 
 void
      ppilLexer->T__41(ppilLexer)
 *  - 
 void
      ppilLexer->T__42(ppilLexer)
 *  - 
 void
      ppilLexer->T__43(ppilLexer)
 *  - 
 void
      ppilLexer->T__44(ppilLexer)
 *  - 
 void
      ppilLexer->T__45(ppilLexer)
 *  - 
 void
      ppilLexer->T__46(ppilLexer)
 *  - 
 void
      ppilLexer->T__47(ppilLexer)
 *  - 
 void
      ppilLexer->T__48(ppilLexer)
 *  - 
 void
      ppilLexer->T__49(ppilLexer)
 *  - 
 void
      ppilLexer->T__50(ppilLexer)
 *  - 
 void
      ppilLexer->T__51(ppilLexer)
 *  - 
 void
      ppilLexer->IDENT(ppilLexer)
 *  - 
 void
      ppilLexer->NUMBER(ppilLexer)
 *  - 
 void
      ppilLexer->COMMENT(ppilLexer)
 *  - 
 void
      ppilLexer->NEWLINE(ppilLexer)
 *  - 
 void
      ppilLexer->WS(ppilLexer)
 *  - 
 void
      ppilLexer->Tokens(ppilLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_pilLexer_H
#define _pilLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct pilLexer_Ctx_struct pilLexer, * ppilLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
pilLexer

 */
struct pilLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__19)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__20)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__21)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__22)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__23)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__24)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__25)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__26)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__27)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__28)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__29)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__30)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__31)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__32)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__33)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__34)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__35)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__36)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__37)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__38)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__39)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__40)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__41)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__42)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__43)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__44)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__45)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__46)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__47)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__48)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__49)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__50)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mT__51)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mIDENT)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mNUMBER)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mNEWLINE)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct pilLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct pilLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct pilLexer_Ctx_struct * ctx);
    void	    (*free)   (struct pilLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API ppilLexer pilLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API ppilLexer pilLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define T__31      31
#define T__32      32
#define T__33      33
#define T__34      34
#define T__35      35
#define T__36      36
#define T__37      37
#define T__38      38
#define T__39      39
#define T__40      40
#define T__41      41
#define T__42      42
#define T__43      43
#define T__44      44
#define T__45      45
#define T__46      46
#define T__47      47
#define T__48      48
#define T__49      49
#define T__50      50
#define T__51      51
#define BLOCK      4
#define BODY      5
#define COMMENT      6
#define FUNCTION      7
#define IDENT      8
#define INP      9
#define INTERVAL      10
#define NEWLINE      11
#define NUMBER      12
#define ORDER      13
#define OUTPUT      14
#define PARAM      15
#define PROOF      16
#define VARIABLE      17
#define WS      18
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for pilLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
